#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 
//
//   fxc /T vs_2_0 /E MyVertexShader /Fh cube_vs.h cube.fx
//
//
// Parameters:
//
//   float4x4 matProj;
//   float4x4 matView;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   matView      c0       4
//   matProj      c4       4
//

    vs_2_0
    dcl_position v0
    dcl_color v1
    dp4 r0.x, v0, c0
    dp4 r0.y, v0, c1
    dp4 r0.z, v0, c2
    dp4 r0.w, v0, c3
    dp4 oPos.x, r0, c4
    dp4 oPos.y, r0, c5
    dp4 oPos.z, r0, c6
    dp4 oPos.w, r0, c7
    mov oD0, v1

// approximately 9 instruction slots used
#endif

const DWORD g_vs20_MyVertexShader[] =
{
    0xfffe0200, 0x0025fffe, 0x42415443, 0x0000001c, 0x0000006b, 0xfffe0200, 
    0x00000002, 0x0000001c, 0x20000100, 0x00000064, 0x00000044, 0x00040002, 
    0x00000004, 0x0000004c, 0x00000000, 0x0000005c, 0x00000002, 0x00000004, 
    0x0000004c, 0x00000000, 0x5074616d, 0x006a6f72, 0x00030003, 0x00040004, 
    0x00000001, 0x00000000, 0x5674616d, 0x00776569, 0x325f7376, 0x4d00305f, 
    0x6f726369, 0x74666f73, 0x29522820, 0x44334420, 0x53203958, 0x65646168, 
    0x6f432072, 0x6c69706d, 0x00207265, 0x0200001f, 0x80000000, 0x900f0000, 
    0x0200001f, 0x8000000a, 0x900f0001, 0x03000009, 0x80010000, 0x90e40000, 
    0xa0e40000, 0x03000009, 0x80020000, 0x90e40000, 0xa0e40001, 0x03000009, 
    0x80040000, 0x90e40000, 0xa0e40002, 0x03000009, 0x80080000, 0x90e40000, 
    0xa0e40003, 0x03000009, 0xc0010000, 0x80e40000, 0xa0e40004, 0x03000009, 
    0xc0020000, 0x80e40000, 0xa0e40005, 0x03000009, 0xc0040000, 0x80e40000, 
    0xa0e40006, 0x03000009, 0xc0080000, 0x80e40000, 0xa0e40007, 0x02000001, 
    0xd00f0000, 0x90e40001, 0x0000ffff
};
