#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 
//
//   fxc /T ps_2_0 /E MyPixelShader /Fh cube_ps.h cube.fx
//
    ps_2_0
    dcl v0
    mov oC0, v0

// approximately 1 instruction slot used
#endif

const DWORD g_ps20_MyPixelShader[] =
{
    0xffff0200, 0x0013fffe, 0x42415443, 0x0000001c, 0x00000023, 0xffff0200, 
    0x00000000, 0x00000000, 0x20000100, 0x0000001c, 0x325f7370, 0x4d00305f, 
    0x6f726369, 0x74666f73, 0x29522820, 0x44334420, 0x53203958, 0x65646168, 
    0x6f432072, 0x6c69706d, 0x00207265, 0x0200001f, 0x80000000, 0x900f0000, 
    0x02000001, 0x800f0800, 0x90e40000, 0x0000ffff
};
